---
title: "NHLScraper"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{NHLScraper}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(NHLScraper)
```

## Draft Data
```{r draft}
draft_rankings_2025 <- get_draft_rankings(year=2025)
draft_picks_2024 <- get_draft_picks(year=2024, round='all')
```

## Game Data
```{r game}
scores_2025_01_01 <- get_scores()
gc_pbp_2024020602 <- get_gc_play_by_play()
boxscore_2024020602 <- get_game_boxscore()
game_story_2024020602 <- get_game_story()
shift_charts_2024020602 <- get_shift_charts()
```

## Goalie Data
```{r goalie}
goalies_20242025 <- get_goalies(
  start_season=20242025, end_season=20242025
)
playoff_savePctg_leaders_20242025 <- get_goalie_leaders(
  season=20242025, category='savePctg'
)
goalie_milestones <- get_goalie_milestones()
playoff_goalie_statistics_20242025 <- get_goalie_statistics(
  season=20242025,
  is_game=T,
  dates=c('2025-05-21', '2025-05-22', '2025-05-23', '2025-05-24', '2025-05-25'),
  game_types=c(3)
)
```

## League Data
```{r league}
standings_2025_01_01 <- get_standings()
schedule_2025_01_01 <- get_schedule()
```

## Other Data
```{r other}
tv_schedule_2025_01_01 <- get_tv_schedule()
partner_odds_latest <- get_partner_odds()
```

## Player Data
```{r player}
Martin_Necas_game_log_20242025 <- get_player_game_log(season=20242025)
Martin_Necas_landing <- get_player_landing()
spotlight_players <- get_spotlight_players()
```

## Playoff Data
```{r playoff}
series_carousel_20242025_1 <- get_series_carousel(season=20242025)
playoff_schedule_TOR_OTT_20242025 <- get_series_schedule(season=20242025)
playoff_bracket_2025 <- get_playoff_bracket(year=2025)
```

## Skater Data
```{r skater}
```

## League Data
```{r league}
```
